# Generated by Django 3.0.6 on 2021-08-12 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Request_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_id', models.IntegerField()),
                ('name', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('service_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Requests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=120)),
                ('date', models.DateTimeField()),
                ('inn', models.IntegerField()),
                ('request_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tunduk_app.Request_type')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tunduk_app.Service')),
            ],
        ),
        migrations.AddField(
            model_name='request_type',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tunduk_app.Service'),
        ),
        migrations.AlterUniqueTogether(
            name='request_type',
            unique_together={('service', 'type_id')},
        ),
    ]
