# Generated by Django 3.0.6 on 2021-08-12 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tunduk_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requests',
            name='request_type',
        ),
        migrations.RemoveField(
            model_name='requests',
            name='service',
        ),
        migrations.DeleteModel(
            name='Request_type',
        ),
        migrations.DeleteModel(
            name='Requests',
        ),
        migrations.DeleteModel(
            name='Service',
        ),
    ]
