# Generated by Django 3.0.6 on 2021-08-18 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tunduk_app', '0004_service_userid'),
    ]

    operations = [
        migrations.AddField(
            model_name='request_type',
            name='method_name',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='membercode',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='sybsystemcode',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='type',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
