# Generated by Django 3.0.6 on 2021-08-18 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tunduk_app', '0005_auto_20210818_1512'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='sybsystemcode',
            new_name='subsystemcode',
        ),
    ]
